# Server
server.port=8080

  # Database - NEON
spring.datasource.url=${DB_URL:jdbc:postgresql://ep-purple-silence-ag2f17f0-pooler.c-2.eu-central-1.aws.neon.tech/neondb?sslmode=require}
spring.datasource.username=${DB_USERNAME:neondb_owner}
spring.datasource.password=${DB_PASSWORD:npg_05VLEBOptxrZ}

  # JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

  # Flyway
spring.flyway.enabled=false



# Redis - Upstash
spring.data.redis.host=${REDIS_HOST:equal-sparrow-20070.upstash.io}
spring.data.redis.port=${REDIS_PORT:6379}
spring.data.redis.password=${REDIS_PASSWORD:AU5mAAIncDIyYWI2ZjFmODMwYjQ0ZWJiYTRiOTA0OTZhNTVjOThjZHAyMjAwNzA}
spring.data.redis.ssl.enabled=true

  # JWT
jwt.secret=${JWT_SECRET:4D635166546A576E5A7234753778214125442A472D4B614E645267556B587032}
jwt.expiration=${JWT_EXPIRATION:86400}

  # Spring Security
spring.security.filter.order=10

  # CORS
cors.allowed-origins=http://localhost:5173

  # Logging
logging.level.com.shop=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO