# Server
server.port=8080

  # Database - NEON
spring.datasource.url=${}
spring.datasource.username=${}
spring.datasource.password=${}

  # JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

  # Flyway
spring.flyway.enabled=false



# Redis - Upstash
spring.data.redis.host=${}
spring.data.redis.port=${}
spring.data.redis.password=${}
spring.data.redis.ssl.enabled=true

  # JWT
jwt.secret=${}
jwt.expiration=${}

  # Spring Security
spring.security.filter.order=10

  # CORS
cors.allowed-origins=http://localhost:5173

  # Logging
logging.level.com.shop=DEBUG
logging.level.org.springframework.security=INFO
logging.level.org.springframework.web=INFO
